#!/bin/bash

if [[ $1 == "-s" ]]; then
  # Run git fetch
  git fetch

  # Run git pull
  git pull

  # Run git add -A
  git add -A

  # Run git commit -a
  echo "Enter the commit message:"
  read commit_message
  git commit -a -m "$commit_message"

  # Run git push origin
  git push origin
else
  # Run git add -A
  git add -A

  # Run git commit -a
  echo "Enter the commit message:"
  read commit_message
  git commit -a -m "$commit_message"

  # Run git push origin
  git push origin
fi
