#!/bin/bash

# Function to echo colored text
function echo_color() {
  local text=$1
  local color_code=$2
  local reset="\e[0m"
  echo -e "${color_code}${text}${reset}"
}

# Function to echo colored command status
function echo_command() {
  local command_name=$1
  local color_code=$2
  local reset="\e[0m"
  echo -e -n "${color_code}RUNNING ${reset}${command_name}"
}

# Check if argument is provided
if [[ $1 == "-s" ]]; then
  # Run git fetch
  echo_command "Fetch" "\e[1;32m"
  git fetch >/dev/null 2>&1
  echo

  # Run git pull
  echo_command "Pull" "\e[1;32m"
  git pull >/dev/null 2>&1
  echo

  # Run git add -A
  echo_command "Add" "\e[1;32m"
  git add -A >/dev/null 2>&1
  echo

  # Run git commit -a
  echo_command "Commit" "\e[1;32m"
  echo -n -e "\n\e[0mEnter the commit message: "
  read commit_message
  git commit -a -m "$commit_message" >/dev/null 2>&1
  echo

  # Run git push origin
  echo_command "Pushing" "\e[1;32m"
  git push origin >/dev/null 2>&1
  echo

else
  # Run git add -A
  echo_command "Add" "\e[1;32m"
  git add -A >/dev/null 2>&1
  echo

  # Run git commit -a
  echo_command "Commit" "\e[1;32m"
  echo -n -e "\e[0mEnter the commit message: "
  read commit_message
  git commit -a -m "$commit_message" >/dev/null 2>&1
  echo

  # Run git push origin
  echo_command "Pushing" "\e[1;32m"
  git push origin >/dev/null 2>&1
  echo
fi

# Print "DONE" indicator in red and bold
echo_color "DONE" "\e[1;31m"
